[package]
name = "node-primitives"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Ladder Network <contact@laddernetwork.io>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/paritytech/substrate", default-features = false }
runtime_primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate", default-features = false }

[dev-dependencies]
substrate-serializer = { git = "https://github.com/paritytech/substrate" }
pretty_assertions = "0.5"

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"primitives/std",
	"rstd/std",
	"runtime_primitives/std",
	"serde",
]
